Basic python


1.split the string

In [28]:
s = "Hi there ibm!"

In [29]:
s.split()

['Hi', 'there', 'ibm!']

2.Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
 planet = "Earth"
diameter = 12742

In [8]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


 3. In this nest dictionary grab the word "hello"

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello ibm']}]}]}

In [13]:
d['k1'][3]['tricky'][3]['target'][3]

'hello ibm'

4.numpy

In [5]:
import numpy as np

4.1 Create an array of 10 zeros?

4.2 Create an array of 10 fives?

In [6]:
array=np.zeros(10)
array1=np.ones(10)*5
print(array)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [7]:
arr=np.arange(20,35,2)
print(arr)

[20 22 24 26 28 30 32 34]



6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
t=np.arange(0,9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate x and y

x= np.array([1, 2, 3]), y = np.array([4, 5, 6])

In [11]:
x = np.array([1, 2])
y = np.array([4, 5])
z=np.concatenate((x,y))
print(z)

[1 2 4 5]


Pandas

8. Create a dataframe with 3 rows and 2 columns

In [10]:
import pandas as pd

In [14]:
x=[1,2]
y=[4,5]
z=[6,7]
data=pd.DataFrame([x,y,z])
data

0  1
0  1  2
1  4  5
2  6  7

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
dates=pd.date_range(start='1-1-2023',end='10-2-2023')
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

10. Create 2D list to DataFrame



lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [26]:
df=pd.DataFrame(lists)

In [27]:
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24