In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score
import warnings
warnings.filterwarnings('ignore')


In [3]:
#checking null values
ds.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [4]:
#SpLitting data as independent and dependent 
#removing index column in independent dataset 
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [5]:
#SpLitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
from sklearn.linear_model import LogisticRegression 
lr=LogisticRegression() 
lr.fit(x_train,y_train) 

LogisticRegression()

In [7]:
#Finding accuracy
y_pred1=lr.predict(x_test) 
from sklearn .metrics import accuracy_score 
log_reg=accuracy_score(y_test, y_pred1) 
log_reg


0.9167797376752601

In [9]:
#knn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [10]:
y_train_knn = knn.predict(x_train)
y_test_knn = knn.predict(x_test)

In [16]:
acc_train_knn = metrics.accuracy_score(y_train,y_train_knn)
acc_test_knn = metrics.accuracy_score(y_test,y_test_knn)
print("Accuracy on training Data: {:.3f}".format(acc_train_knn))
print("Accuracy on test Data: {:.3f}".format(acc_test_knn))
print()

Accuracy on training Data: 0.988
Accuracy on test Data: 0.963



In [18]:
# Gradient Boosting Classifier Model
from sklearn.ensemble import GradientBoostingClassifier

# instantiate the model
gbc = GradientBoostingClassifier(max_depth=4,learning_rate=0.7)

# fit the model 
gbc.fit(x_train,y_train)

GradientBoostingClassifier(learning_rate=0.7, max_depth=4)

In [20]:
#predicting the target value from the model for the samples
y_train_gbc = gbc.predict(x_train)
y_test_gbc = gbc.predict(x_test)

In [22]:
acc_train_gbc = metrics.accuracy_score(y_train,y_train_gbc)
acc_test_gbc = metrics.accuracy_score(y_test,y_test_gbc)
print("Accuracy on training Data: {:.3f}".format(acc_train_gbc))
print("Accuracy on test Data: {:.3f}".format(acc_test_gbc))
print()

Accuracy on training Data: 0.987
Accuracy on test Data: 0.973



In [26]:
#saving the model as pkl file
import pickle
pickle.dump(lr,open('model.pkl','wb'))